name: Web Monitor

on:
  # Run daily at 00:00 UTC
  schedule:
    - cron: '0 0 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.3'
        bundler-cache: true
    
    - name: Run web monitor
      run: |
        bundle exec ruby scripts/monitor.rb
    
    - name: Configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Commit changes
      run: |
        git add docs/data/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update monitoring data - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push
        fi